FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache postgresql-client

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

EXPOSE 3000 9229
